# Generated by Django 4.2 on 2024-01-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('des', models.CharField(blank=True, max_length=255, null=True)),
                ('resume', models.CharField(blank=True, max_length=255, null=True)),
                ('accepted', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
